[project]
name = "lan-to-zotero"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "playwright>=1.52.0",
    "pyzotero>=1.6.11",
    "requests>=2.32.3",
    "zolocal>=0.2.0",
]
